on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      working-directory: ./42TESTERS-PRINTF
    - name: run_test
      run: bash run_test.sh
      working-directory: ./42TESTERS-PRINTF
