on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      working-directory: ./42TESTERS-PRINTF
    - name: runtest
      run: ./runtest.sh
      working-directory: ./42TESTERS-PRINTF
